version: "3.1"
services:
  zookeeper:
    image: zookeeper
    ports: 
      - 2181:2181
    networks:
      - api
    restart: always 

  kafka:
    image: wurstmeister/kafka
    ports: 
      - 9092:9092
    environment: 
      KAFKA_CREATE_TOPICS: "business:1:1"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on: 
      - zookeeper
    networks: 
      - api

  accounts-db:
    image: mongo
    volumes: 
      - ./tmp/nkapsi-accounts-db:/data/db
    restart: always
    networks:
      - accounts

  accounts:
    build: https://github.com/maelfosso/authentication-kafka
    image: nkapsi/api-accounts
    command: bundle exec karafka server
    volumes:
      - ./accounts:/app
    ports:
      - 5000:3000
    environment: 
      MONGO_HOSTNAME: accounts-db
      KAFKA_HOSTNAME: kafka
    depends_on:
      - kafka
      - accounts-db
    networks:
      - accounts
      - api

  business-db:
    image: mongo
    restart: always
    volumes:
      - ./tmp/nkapsi-business-db:/data/db
    networks:
      - business
      - api
      
  business:
    build: https://github.com/maelfosso/nkapsi-business
    image: nkapsi/api-business
    volumes:
      - ./business:/usr/src/app
    ports:
      - 4000:3000
    environment: 
      MONGO_HOSTNAME: business-db
      KAFKA_HOSTNAME: kafka
    depends_on:
      - kafka
      - business-db
    networks:
      - business
      - api

networks:
  accounts:
  business:
  api:

